(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var f,aa="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},ba=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");},ca=ba(this),h;
if("function"==typeof Object.setPrototypeOf)h=Object.setPrototypeOf;else{var l;a:{var da={a:!0},m={};try{m.__proto__=da;l=m.a;break a}catch(a){}l=!1}h=l?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var n=h,p=this||self,ea=/^[\w+/_-]+[=]{0,2}$/,q=null,t=function(a){return(a=a.querySelector&&a.querySelector("script[nonce]"))&&(a=a.nonce||a.getAttribute("nonce"))&&ea.test(a)?a:""},u=function(a){var b=typeof a;return"object"!=b?b:a?Array.isArray(a)?"array":b:"null"},v=function(a,b){function c(){}c.prototype=b.prototype;a.Ua=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Wa=function(d,e,k){for(var g=Array(arguments.length-2),r=2;r<arguments.length;r++)g[r-2]=arguments[r];return b.prototype[e].apply(d,
g)}},w=function(a){return a};var x=function(a,b,c){a=parseInt(a.getAttribute(b),10);isNaN(a)&&(a=c);return a},y=function(a,b,c){return a.hasAttribute(b)?a.getAttribute(b):c};var z=function(a,b){this.Ta=a;this.oa=b};z.prototype.fetch=function(){navigator.geolocation.getCurrentPosition(this.Ma.bind(this),this.Ca.bind(this))};z.prototype.Ma=function(a){a=a.coords;this.Ta(a.latitude,a.longitude,a.accuracy)};z.prototype.Ca=function(a){this.oa(a.message)};var A=function(a,b,c){c=void 0===c?null:c;var d=document.createEvent("CustomEvent");d.initCustomEvent(a,!0,!0,c);b.dispatchEvent(d);return d},fa=function(a,b){var c=function(d){a.removeEventListener("load",c);b(d)};a.addEventListener("load",c)};function B(a){if(Error.captureStackTrace)Error.captureStackTrace(this,B);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))}v(B,Error);B.prototype.name="CustomError";var C=function(a,b){a=a.split("%s");for(var c="",d=a.length-1,e=0;e<d;e++)c+=a[e]+(e<b.length?b[e]:"%s");B.call(this,c+a[d])};v(C,B);C.prototype.name="AssertionError";var ha=function(a,b,c){if(!a){var d="Assertion failed";if(b){d+=": "+b;var e=Array.prototype.slice.call(arguments,2)}throw new C(""+d,e||[]);}return a},D=function(a,b){throw new C("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));};var E=function(a,b){a:{try{var c=a&&a.ownerDocument,d=c&&(c.defaultView||c.parentWindow);d=d||p;if(d.Element&&d.Location){var e=d;break a}}catch(g){}e=null}if(e&&"undefined"!=typeof e[b]&&(!a||!(a instanceof e[b])&&(a instanceof e.Location||a instanceof e.Element))){e=typeof a;if("object"==e&&null!=a||"function"==e)try{var k=a.constructor.displayName||a.constructor.name||Object.prototype.toString.call(a)}catch(g){k="<object could not be stringified>"}else k=void 0===a?"undefined":null===a?"null":
typeof a;D("Argument is not a %s (or a non-Element, non-Location mock); got: %s",b,k)}};var F;var I=function(a,b){this.$=a===G&&b||"";this.ka=H};I.prototype.S=!0;I.prototype.M=function(){return this.$};I.prototype.toString=function(){return"Const{"+this.$+"}"};var H={},G={};var K=function(a,b){this.X=b===J?a:""};K.prototype.S=!0;K.prototype.M=function(){return this.X.toString()};K.prototype.toString=function(){return this.X+""};var J={};var M=function(a,b){this.W=b===L?a:""};M.prototype.S=!0;M.prototype.M=function(){return this.W.toString()};M.prototype.toString=function(){return this.W.toString()};
var N=function(a){if(a instanceof M&&a.constructor===M)return a.W;D("expected object of type SafeUrl, got '"+a+"' of type "+u(a));return"type_error:SafeUrl"},ia=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i,O=function(a){if(a instanceof M)return a;a="object"==typeof a&&a.S?a.M():String(a);ha(ia.test(a),"%s does not match the safe URL pattern",a)||(a="about:invalid#zClosurez");return new M(a,L)},L={};var P=function(a,b){E(a,"HTMLAnchorElement");b=b instanceof M?b:O(b);a.href=N(b)},Q=function(a){a=a instanceof M?a:O(a);p.open(N(a),"")};var R=function(){this.Sa="https://www.google.com/jsapi";for(var a=["google","load"],b=window,c=0;b&&c<a.length;c++)b=b[a[c]];this.D=b?0:2;this.F=[]};R.prototype.Ja=function(){for(var a=this.D=0;a<this.F.length;a++)this.F[a]();this.F=[]};
R.prototype.load=function(a){a&&(0==this.D?a():this.F.push(a));if(2==this.D){this.D=1;var b=document;a="SCRIPT";"application/xhtml+xml"===b.contentType&&(a=a.toLowerCase());a=b.createElement(a);fa(a,this.Ja.bind(this));a.setAttribute("type","text/javascript");a.setAttribute("async",!0);b=this.Sa;if(void 0===F){var c=null;var d=p.trustedTypes;if(d&&d.createPolicy)try{c=d.createPolicy("goog#html",{createHTML:w,createScript:w,createScriptURL:w})}catch(e){p.console&&p.console.error(e.message)}F=c}b=(c=
F)?c.createScriptURL(b):b;b=new K(b,J);E(a,"HTMLScriptElement");b instanceof K&&b.constructor===K?b=b.X:(D("expected object of type TrustedResourceUrl, got '"+b+"' of type "+u(b)),b="type_error:TrustedResourceUrl");a.src=b;(b=a.ownerDocument&&a.ownerDocument.defaultView)&&b!=p?b=t(b.document):(null===q&&(q=t(p.document)),b=q);b&&a.setAttribute("nonce",b);(b=document.getElementsByTagName("script")[0])?b.parentNode.insertBefore(a,b):document.getElementsByTagName("head")[0].appendChild(a)}};var S=null,ja=function(a){S||(S=new R);S.load(function(){google.load("maps","3.28",a)})};var ka=function(a,b){this.Oa=a;this.Na=new google.maps.places.PlacesService(b)};ka.prototype.search=function(a,b,c){a={location:a.getCenter()||void 0,radius:3*a.getRadius(),query:this.Oa};this.Na.textSearch(a,function(d,e){c(e==google.maps.places.PlacesServiceStatus.OK?d:[])})};var T=function(a){a=a.trim();return window.Enabler?window.Enabler.getUrl(a):a};var U=function(a,b,c,d,e,k,g){this.R=a;this.g=null;this.Pa=c;this.wa=d;this.xa=e;this.Qa=k;this.i=g;this.va=g.limit;this.Y=g.radius;this.ca=null;this.v=0;this.l=this.B=this.ea=this.O=this.P=this.L=this.ha=this.ba=this.U=null;this.m=[];this.H=[];this.ja=null;this.h=b.ownerDocument.createElement("div");this.h.className="map";b.appendChild(this.h)},la=function(a,b,c){var d=a.h.ownerDocument.createElement("img"),e=function(){d.removeEventListener("load",e,!1);d.removeEventListener("error",e,!1);d.removeEventListener("abort",
e,!1);c()};d.addEventListener("load",e,!1);d.addEventListener("error",e,!1);d.addEventListener("abort",e,!1);d.setAttribute("src",T(b))};
U.prototype.na=function(){this.v--;if(0==this.v){var a=this.i;if(a.lat&&a.lng){var b=new google.maps.LatLng(a.lat,a.lng);var c=a.zoom;var d=!0}else b=new google.maps.LatLng(0,0),c=1;c=new google.maps.Map(this.h,{center:b,zoom:c,mapTypeId:google.maps.MapTypeId.ROADMAP,mapTypeControl:!1});this.ja=c.getBounds();google.maps.event.addListener(c,"dragend",this.Ba.bind(this));google.maps.event.addListener(c,"click",this.Ka.bind(this));var e=T(this.i.markerSource);this.U={url:e,size:new google.maps.Size(34,
34),origin:new google.maps.Point(0,0)};this.ba={url:e,size:new google.maps.Size(34,34),origin:new google.maps.Point(34,0)};this.ha={url:e,size:new google.maps.Size(37,34),origin:new google.maps.Point(68,0),anchor:new google.maps.Point(10,34)};this.P={url:T(this.i.gpsIconSource),size:new google.maps.Size(32,32),anchor:new google.maps.Point(0,0)};this.ca=new ka(a.query||"*",c);d&&new google.maps.Marker({position:b,map:c,icon:this.P});this.g=c;this.Pa()}};
U.prototype.Ba=function(){if(this.B){for(var a=this.g.getBounds(),b=!0,c=0;c<this.H.length;c++)if(a.contains(this.H[c].geometry.location||null)){b=!1;break}b&&!this.B.getBounds().contains(this.g.getCenter())&&(this.C(),this.Qa())}};U.prototype.C=function(){this.l&&(this.l.setIcon(this.U),this.l=null)};
var ma=function(a,b,c,d){a.g&&(b=new google.maps.LatLng(b,c),c=a.g,a.O=b,c.setCenter(b),new google.maps.Marker({position:b,map:c,icon:a.P}),d&&(a.Y=d,a.ea=new google.maps.Circle({center:b,radius:a.Y,map:c,fillColor:"#a2d1f5",fillOpacity:.5,strokeWeight:0}),c.fitBounds(a.ea.getBounds())))};f=U.prototype;f.search=function(a){if(this.g){var b=this.Y,c=10-this.g.getZoom();0<c&&(b*=c);this.B=new google.maps.Circle({center:this.g.getCenter(),radius:b});this.ca.search(this.B,this.va,this.G.bind(this,a))}};
f.G=function(a,b){for(var c=0;c<this.m.length;c++)this.m[c].setMap(null),google.maps.event.clearInstanceListeners(this.m[c]);this.m.length=0;this.H=b;for(c=0;c<b.length;c++){var d=new google.maps.Marker({position:b[c].geometry.location,map:this.g,icon:this.U,Xa:this.ha});google.maps.event.addListener(d,"click",this.V.bind(this,c));this.m.push(d)}this.g.fitBounds(this.B.getBounds());if(c=0<b.length)d=this.g.getBounds(),b=b[0].geometry.location||null,d&&!d.contains(b)&&(d.extend(b),this.g.fitBounds(d));
a(c)};f.Ka=function(){this.C();this.wa()};f.V=function(a){this.C();this.l=this.m[a];this.xa(this.H[a],this.pa.bind(this))};f.pa=function(a){this.l.setIcon(this.ba);this.g.panTo(this.l.getPosition());this.g.panBy(0,a)};f.ta=function(a,b,c,d){d==google.maps.GeocoderStatus.OK?(b=c[0].geometry.location,this.g.setCenter(b),this.g.fitBounds(c[0].geometry.viewport),ma(this,b.lat(),b.lng()),a()):b()};var W=function(a,b,c,d){this.R=a;this.K=null;this.ma=c;this.sa=d;this.h=b.ownerDocument.createElement("div");this.h.className="ip";a=b.ownerDocument.createElement("div");a.className="bg";this.h.appendChild(a);c=b.ownerDocument.createElement("a");c.className="dir";c.appendChild(b.ownerDocument.createElement("div"));a.appendChild(c);c.addEventListener("click",this.Ia.bind(this),!1);c=b.ownerDocument.createElement("div");c.className="res";this.aa=b.ownerDocument.createElement("div");this.aa.className=
"title";this.J=b.ownerDocument.createElement("div");this.J.className="address";this.A=b.ownerDocument.createElement("div");this.A.className="tel";d=this.o=b.ownerDocument.createElement("a");var e=new I(G,"#");e instanceof I&&e.constructor===I&&e.ka===H?e=e.$:(D("expected object of type Const, got '"+e+"'"),e="type_error:Const");P(d,new M(e,L));this.A.appendChild(this.o);c.appendChild(this.aa);c.appendChild(this.J);c.appendChild(this.A);a.appendChild(c);this.o.addEventListener("click",this.ya.bind(this));
c=b.ownerDocument.createElement("a");c.className="close";c.appendChild(b.ownerDocument.createElement("div"));a.appendChild(c);c.addEventListener("click",this.za.bind(this),!1);V(this);b.appendChild(this.h)},V=function(a){a.h.classList.add("hidden")};W.prototype.ya=function(a){a.preventDefault();a=this.o.href;A("calllocation",this.R,{url:a}).detail.handled||Q(a)};W.prototype.za=function(a){a.preventDefault();V(this);this.ma()};W.prototype.Ia=function(a){a.preventDefault();this.K&&this.sa(this.K)};var na=function(a){var b=document.createElement("div");b.className="bg hidden";var c=document.createElement("div");c.className="loading";c.appendChild(document.createElement("div"));b.appendChild(c);this.h=b;a.appendChild(this.h)};na.prototype.show=function(){this.h.classList.remove("hidden")};var oa=function(a){return"gwd-page"==a.tagName.toLowerCase()||"gwd-page"==a.getAttribute("is")},pa=function(a){if(oa(a))return a;for(;a&&9!=a.nodeType;)if((a=a.parentElement)&&oa(a))return a;return null};var ra=function(a,b,c,d){this.N=b;this.ra=c;this.h=qa(this,d);this.qa=this.h.querySelector("form");this.ua=this.h.querySelector("input");this.Va=this.h.querySelector(".title");this.la=this.h.querySelector(".btns");a.appendChild(this.h)},qa=function(a,b){var c=document.createElement("div"),d=document.createElement("div");d.classList.add("diag");c.appendChild(d);var e=document.createElement("div");e.classList.add("title");e.textContent=b.title;d.appendChild(e);e=document.createElement("div");e.classList.add("btns");
d.appendChild(e);var k=document.createElement("form");k.setAttribute("method","get");d.appendChild(k);var g=document.createElement("input");g.placeholder=b.geocodePlaceholder;g.type="search";k.appendChild(g);a.N?(sa(e,b.gpsLabel,a.N),sa(e,b.geocodeLabel,a.Z.bind(a,b.geocodeTitle))):e.classList.add("hidden");b=c.querySelector("form");b.addEventListener("submit",function(r){r.preventDefault();this.ra(g.value)}.bind(a),!1);a.N&&b.classList.add("hidden");c.classList.add("bg");return c},sa=function(a,
b,c){var d=document.createElement("a");d.textContent=b;d.addEventListener("click",function(e){e.preventDefault();c()},!1);d.setAttribute("href","#");a.appendChild(d)};ra.prototype.Z=function(a){this.Va.textContent=a;this.la.classList.add("hidden");this.qa.classList.remove("hidden");this.h.classList.remove("hidden");this.ua.focus()};var ta=["start-latitude","start-longitude","query"],X=function(){var a=HTMLElement.call(this)||this;a.ga=!1;a.T=!1;a.fa=!1;return a},Y=HTMLElement;X.prototype=aa(Y.prototype);X.prototype.constructor=X;if(n)n(X,Y);else for(var Z in Y)if("prototype"!=Z)if(Object.defineProperties){var ua=Object.getOwnPropertyDescriptor(Y,Z);ua&&Object.defineProperty(X,Z,ua)}else X[Z]=Y[Z];X.Ua=Y.prototype;f=X.prototype;
f.connectedCallback=function(){if(!this.g){for(;this.firstChild;)this.removeChild(this.firstChild);var a={geocodeFailure:y(this,"msg-geocode-failure","Your location could not be determined. Please enter a valid address."),gpsIconSource:y(this,"gps-src","assets/location.png"),limit:x(this,"result-limit",20),locationDialogConfig:{title:y(this,"msg-start-position-prompt","How would you like us to get your position?"),gpsLabel:y(this,"msg-gps-button-label","Use GPS"),geocodeLabel:y(this,"msg-manual-position-button-label",
"Enter address or zip code"),geocodeTitle:y(this,"msg-manual-position-prompt","Enter address or zip code"),geocodePlaceholder:y(this,"msg-manual-position-placeholder","Address or zip code")},markerSource:y(this,"marker-src","assets/marker_sprite.png"),noResultsError:y(this,"msg-no-results-found","No results found near you."),radius:x(this,"search-radius",4E4),requestLocation:this.hasAttribute("request-user-location")||!this.hasAttribute("start-latitude")||!this.hasAttribute("start-longitude"),zoom:x(this,
"start-zoom",16),showLocationBar:this.hasAttribute("show-location-bar"),includeDirections:this.hasAttribute("include-directions"),includeClickToCall:this.hasAttribute("include-click-to-call"),includeDrapeImage:this.hasAttribute("include-drape-image")};this.hasAttribute("query")&&(a.query=this.getAttribute("query"));this.hasAttribute("start-latitude")&&(a.lat=parseFloat(this.getAttribute("start-latitude")));this.hasAttribute("start-longitude")&&(a.lng=parseFloat(this.getAttribute("start-longitude")));
this.hasAttribute("client-id")&&(a.clientId=this.getAttribute("client-id"));this.hasAttribute("api-key")&&(a.apiKey=this.getAttribute("api-key"));a.showLocationBar&&this.hasAttribute("location-bar-color")&&(a.locationBarColor=this.getAttribute("location-bar-color"));a.includeDrapeImage&&this.hasAttribute("drape-image-source")&&(a.drapeImageSource=this.getAttribute("drape-image-source"));this.i=a;var b=this.ownerDocument.createElement("div");b.className="sizer";this.g=new U(this,b,this.La.bind(this),
this.ia.bind(this),this.V.bind(this),this.I.bind(this),a);this.da=navigator.geolocation?new z(this.Ha.bind(this),this.Fa.bind(this)):null;this.u=new ra(b,this.da&&this.Ga.bind(this),this.Ea.bind(this),a.locationDialogConfig);a.requestLocation||V(this.u);this.j=new na(b);this.appendChild(b);this.Ra=b}this.gwdIsLoaded()||((a=pa(this))?a.gwdIsLoaded()&&this.gwdLoad():this.gwdLoad());this.gwdIsActive()||((a=pa(this))?a.gwdIsActive()&&this.gwdActivate():this.gwdActivate());a=this.g;a.g&&google.maps.event.trigger(a.g,
"resize")};f.attributeChangedCallback=function(a,b,c){if(this.g)switch(a){case "query":this.g.i.query=c||"";break;case "start-latitude":this.g.i.lat=parseFloat(c);break;case "start-longitude":this.g.i.lng=parseFloat(c)}};
f.gwdLoad=function(){if(!this.fa){this.fa=!0;var a=this.g,b=a.na.bind(a);a.v=2;la(a,a.i.markerSource,b);a.v++;la(a,a.i.gpsIconSource,b);a.v++;var c=a.i.clientId;a=a.i.apiKey;var d="";a&&!c&&(d="&key="+a);ja({callback:b,other_params:"sensor=true&libraries=places"+(c?"&client="+c:"")+d});b()}};f.gwdIsLoaded=function(){return this.ga};f.gwdActivate=function(){this.classList.remove("deactivated");this.T=!0};f.gwdDeactivate=function(){this.classList.add("deactivated");this.T=!1};f.gwdIsActive=function(){return this.T};
f.setCenter=function(a,b,c){V(this.j);ma(this.g,a,b,c);this.I()};f.La=function(){this.i.requestLocation||this.I();this.classList.add("ready");this.ga=!0;A("ready",this)};f.Ga=function(){this.j.show();V(this.u);this.da.fetch()};f.Ha=function(a,b,c){this.setCenter(a,b,c)};f.Fa=function(a){V(this.j);this.u.Z(a)};f.Ea=function(a){this.j.show();V(this.u);var b=this.g,c=this.I.bind(this),d=this.Da.bind(this);b.g&&(b.L||(b.L=new google.maps.Geocoder),b.L.geocode({address:a,bounds:b.ja},b.ta.bind(b,c,d)))};
f.I=function(){this.i.query?(this.j.show(),this.g.search(this.G.bind(this))):V(this.j);this.ia();A("mapopen",this)};f.G=function(a){V(this.j);a?A("resultsfound",this):(this.u.Z(this.i.geocodeFailure),A("resultsnotfound",this))};f.Da=function(){this.G(!1)};f.ia=function(){this.s&&V(this.s)};
f.V=function(a,b){this.s||(this.s=new W(this,this.Ra,this.g.C.bind(this.g),this.Aa.bind(this)));var c=this.s;c.K=a;c.aa.textContent=a.name;var d=a.vicinity||a.formatted_address;d=d.replace(/, /,",\n");c.J.textContent=d;if(a.formatted_phone_number){c.A.classList.remove("hidden");c.o.textContent=a.formatted_phone_number;d="tel:"+a.formatted_phone_number.replace(/[^\d]/g,"");var e=String(d.substr(0,4)).toLowerCase();0==("tel:"<e?-1:"tel:"==e?0:1)||(d="about:invalid#zClosurez");P(c.o,new M(d,L))}else c.A.classList.add("hidden");
c.h.classList.remove("hidden");b(this.s.h.firstChild.offsetHeight/2);b=a.geometry.location.lat();a=a.geometry.location.lng();A("pinclick",this,{lat:b,lng:a})};f.Aa=function(a){var b=this.g;if(b.g){var c=b.O?b.O.toString():"";a=encodeURIComponent(a.formatted_address);c="https://maps.google.com/maps?saddr="+escape(c)+"&daddr="+a;A("getdirections",b.R,{url:c}).detail.handled||Q(c)}};ca.Object.defineProperties(X,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return ta}}});
customElements.define("gwd-map",X);}).call(this);
